import { v4 as uuidv4 } from "uuid";
import type { AppDocument, Chat, ChatMessage, DocumentType } from "@/types";

/**
 * In-memory mock "database". This module exists purely so the UI is fully
 * interactive without a backend. Every shape here matches the real
 * PostgreSQL tables described in BACKEND_IMPLEMENTATION_GUIDE.md, so
 * `lib/api.ts` can be repointed at FastAPI later with no UI changes.
 */

class MockStore {
  documents: AppDocument[] = [];
  chats: Chat[] = [];
  messages: Record<string, ChatMessage[]> = {};

  reset() {
    this.documents = [];
    this.chats = [];
    this.messages = {};
  }
}

export const mockStore = new MockStore();

export function createMockDocument(
  userId: string,
  fileName: string,
  fileType: DocumentType,
  fileSizeBytes: number,
): AppDocument {
  const doc: AppDocument = {
    id: uuidv4(),
    userId,
    organizationId: null,
    fileName,
    fileType,
    fileSizeBytes,
    status: "uploading",
    statusMessage: null,
    pageCount: null,
    chunkCount: null,
    uploadedAt: new Date().toISOString(),
    processedAt: null,
  };
  mockStore.documents.unshift(doc);
  return doc;
}

export function createMockChat(userId: string, title: string, documentIds: string[]): Chat {
  const chat: Chat = {
    id: uuidv4(),
    userId,
    title,
    documentIds,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
  mockStore.chats.unshift(chat);
  mockStore.messages[chat.id] = [];
  return chat;
}

/** Generates a plausible canned answer referencing uploaded documents,
 *  standing in for the real Ollama + ChromaDB RAG response. */
export function generateMockAnswer(question: string, documents: AppDocument[]): {
  content: string;
  citations: ChatMessage["citations"];
} {
  const readyDocs = documents.filter((d) => d.status === "ready");

  if (readyDocs.length === 0) {
    return {
      content:
        "I don't have any processed documents to search yet. Upload a PDF, DOCX, or Markdown file and I'll answer questions based on its contents.",
      citations: [],
    };
  }

  const primary = readyDocs[0];
  return {
    content: `Based on **${primary.fileName}**, here's what I found relevant to "${question}":\n\nThis is a simulated response from the mock API layer. Once connected to the FastAPI backend, this will be a real answer generated by a local Ollama model (Llama 3, Qwen, or Mistral) grounded in the chunks retrieved from ChromaDB for your uploaded documents.\n\nKey points the real pipeline would surface:\n- Relevant passages retrieved via semantic search over document embeddings\n- A grounded answer composed from those passages only\n- Source citations with page numbers so you can verify the answer`,
    citations: readyDocs.slice(0, 2).map((doc, i) => ({
      documentId: doc.id,
      fileName: doc.fileName,
      page: doc.fileType === "pdf" ? i + 2 : null,
      snippet:
        "...the relevant excerpt retrieved from this document would appear here, trimmed to the matching passage...",
      score: 0.91 - i * 0.08,
    })),
  };
}
